apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-todo-app
  template:
    metadata:
      labels:
        app: django-todo-app
    spec:
      containers:
      - name: django-todo-app
        image: django-todo-app
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "myproject.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: django-todo-app-service
spec:
  selector:
    app: django-todo-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
